### ISSUE TITLE
No module named 'libpysal.api' found when I tried to import

### ISSUE THREAD

**Issue by renanxcortes** [knaaptime/geosnap#1]
Hello,

When I tried to import the function read_ltdb using the following command:

```
from osnap.data import read_ltdb
```

I got these errors:

![image](https://user-images.githubusercontent.com/22593188/47189477-a317d700-d2f1-11e8-9c11-d5cf9f0ed948.png)

![image](https://user-images.githubusercontent.com/22593188/47189876-87adcb80-d2f3-11e8-9c97-b782e2e9f413.png)

In this case I need to manually change this line in 'heuristics.py' and util.py, but perhaps it would be nice if this intermediate step was not necessary.

Kind regards,
Renan

**Comment by knaaptime** [comment]
closing in favor of https://github.com/spatialucr/osnap/issues/8
